version: '3.8'
services:
  client:
    image: clientside:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - shared-network

  server:
    image: serverside:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - shared-network
      
networks:
  shared-network:
    driver: bridge